name: Get and Cache dependencies
description: this is being done to demonstrate the feature of custom composite action
inputs:
  caching:
    description: 'Whether caching is needed or not'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cash was being used or not'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      shell: bash